version: 2
jobs:
  abas:
    docker:
      - image: elixir:1.11.4

    steps:
    - checkout
    - run: rm -rf /../../.dockerenv
    - run: rm -rf /../../dev
    - run: apt update -y


workflows:
  version: 2
  abas:
    jobs:
    - abas
